# https://github.com/tauri-apps/tauri-action/blob/dev/examples/publish-to-auto-release.yml
name: 'client-publish'

on:
  push:
    tags:
      - 'client@*'

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile # change this to npm, pnpm or bun depending on which one you use.

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/client@}" >> $GITHUB_ENV
        shell: bash

      # for cross-platform build compat, use perl
      - name: Update the Tauri App version with tag version
        run: |
          perl -pi -e 's/^version = ".*"/version = "${{ env.VERSION }}"/' apps/client/src-tauri/Cargo.toml

      - name: install git-cliff
        run: cargo install git-cliff || true

      - name: Generate changelog
        id: changelog
        shell: bash
        run: |
          {
            echo 'changelog<<EOF'
            git-cliff \
              --latest \
              --strip all \
              --use-branch-tags \
              --tag-pattern 'client@*' \
              --include-path "apps/client/**/*" \
            | sed -E \
                -e 's/^-[[:space:]]*\*\(client\)\*[[:space:]]*/- /' \
                -e 's/^-[[:space:]]*\*\(client\//- *(/'
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ./apps/client
          tagName: client@${{ env.VERSION }}
          releaseName: client@${{ env.VERSION }}
          releaseBody: '${{ steps.changelog.outputs.changelog }}'
          releaseDraft: true
          prerelease: true
          args: ${{ matrix.args }}
